on: [push]
uses: ubuntu-latest

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        run: |
          pip3 install unittest
          pip3 install -r requirements.txt
          
      - name: tests
        run: |
          test_suite.sh
